---
title: AI Strategy's core pillars
author: "Stefan Langenbach"
lang: en-US
format:
    typst:
        papersize: a4
        margin:
            top: 0.5cm
            left: 1.5cm
            right: 1.5cm
            bottom: 0.5cm
        mainfont: "Helvetica"
        columns: 2
        toc: false
        number-sections: false
        page-numbering: false

---

# Purpose

- **Enable** all employees to generate value by solving domain-specific business challenges using AI without relying on centralized support.

# Organization

- Build a core team of 3 individuals focusing on use case identification, stakeholder management, and AI enablement.
- The core team **enables** departments to use AI effectively to implement solutions in a decentralized manner.

# Roadmap

## Short (1-3 months)

- Define and communicate AI Strategy.
- Define framework to identify, evaluate and prioritize use cases.
- Identify key stakeholders and develop strong relationships with them.
- Compile initial use case portfolio.

## Mid (4-8 months)

- Implement 3 quick wins to realize value from AI.
- Enable 3 departments to solve business challenges using AI without relying on centralized support.
- Distill insights from quick-wins and enablement into playbooks to be distributed and applied to additional departments.

## Long (9+ months)

- Realize quantifiable economic value from implementing AI use cases.
- Ideally render centralized team superfluous.

# Priority Business Areas

- Business areas are selected based on **impact** (economic value), **feasibility** (willingness to collaborate, complexity of use cases, data quality and availability, etc.) and **risk** (probability and impact of of AI making mistakes).
- Start with Customer Care (analyzing tickets) and Software Engineering/IT (implementing features, automating routine processes, etc.).
- Using AI in Customer Care has huge potential to increase efficiency and delight customers. AI excels at dealing with text data and the impact of AI mistakes is relatively low.
- Software Engineering/IT will be completely transformed by AI. The gains from using AI are enormous, the barrier to adoption is low and AI champions possibly already exist.

# Success Metrics & KPIs

- Metrics need to focus on **engagement** (Sign-off on use case roadmap, percentage of departments with AI champion, etc.), **impact** (economic value identified, verified and realized), **momentum** (number of AI use cases shipped to production), and **sentiment** (stakeholder confidence in AI strategy).
- The key metric will be number of use cases shipped to production that deliver measurable economic value.

# Build-vs-Buy

- Build-vs-buy decisions must be evaluated according to total **costs** (TCO), **timeline** to value, **lock-in** risk, and **maturity** of the underlying technology
- As AI is a powerful, yet immature and potentially insecure technology, lock-in risk and maturity are especially important.

# Stakeholder Management

- The general mode of operation for the central team is **transparency first**. Every stakeholder must be able to retrieve information on strategy, use cases, playbooks, etc. via self service.
- While the C-Level team is briefed at least monthly, communication cadence and format will vary by audience.
- For departments close to AI (technology or use case wise) a bi-weekly JourFixe is set up.
- Additionally the core team will host office hours in order to support the self-service approach.
